# Generated by Django 3.1.2 on 2020-11-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20201108_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tage',
        ),
        migrations.AddField(
            model_name='product',
            name='tage',
            field=models.ManyToManyField(to='first.Tag'),
        ),
    ]
