# Generated by Django 3.1.2 on 2020-11-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20201110_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
