# Generated by Django 3.1.2 on 2020-11-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20201110_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_create',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tage',
            new_name='tags',
        ),
    ]
